DROP TABLE GOODS IF EXISTS;
 
CREATE TABLE BOARD (
    BOARD_ID INT NOT NULL PRIMARY KEY,
    WRITER VARCHAR(50) NOT NULL,
    TITLE VARCHAR(50) NOT NULL,
    CONTENT VARCHAR(1000) NOT NULL,
    REG_DATE TIMESTAMP NOT NULL,
    UPDATE_DATE TIMESTAMP ,
    DELETE_DATE TIMESTAMP
);